Updated for release 14.0.8

diff --git a/Core/tdeedu/tdeedu.SlackBuild b/Core/tdeedu/tdeedu.SlackBuild
--- a/Core/tdeedu/tdeedu.SlackBuild
+++ b/Core/tdeedu/tdeedu.SlackBuild
@@ -36,72 +36,77 @@ untar_fn
 ## patch for kig python scripting error:
 ## kig: /usr/include/boost/python/object_core.hpp:422: boost::python::api::object_base::~object_base(): Assertion `Py_REFCNT(m_ptr) > 0' failed.
 ## Re: https://bugs.kde.org/show_bug.cgi?id=401512#c5
-echo $'
+patch -N -p0 << EOF || true
 --- kig/scripting/python_scripter.cc
 +++ kig/scripting/python_scripter.cc
 @@ -493,0 +494 @@
 +      Py_XINCREF((objectvect.begin() +i)->ptr());
-' | while read line
-do
-patch -N -p0
-done || true
+EOF
 
-## for 14.0.7, already done in cgit
+## for 14.0.8, already done in cgit
 sed -i 's|Nome del file di input|Input filename|' kig/pykig/pykig.py
+
+## add some files to html docs
+sed -i 's|*.png|& *.svgz README|' cmake/modules/TDEMacros.cmake
 
 listdocs_fn
 
-## There are issues building with cmake - see README
-USE_CMAKE_EDU=${USE_CMAKE_EDU:-no}
-
-[[ $USE_CMAKE_EDU == no ]] && {
-
-## patch for the libboost_python soname as used in Slackware
-sed -i 's|for bplib in|& "-lboost_python${PYVERSHORT%.*}${PYVERSHORT#*.}"|' kig/configure.in.in
-## and for kig python scripting support with cgit build
-[[ $TDEVERSION == cgit ]] && \
-sed -i 's|$qt_libraries|$tqt_libraries|' kig/configure.in.in
-
-## include all keyboards for ktouch
-(cd ktouch/keyboards/
-sed -i '/keyboard_DATA/q' Makefile.am
-echo $(ls *keyboard) >> Makefile.am)
-
-## add sk data to klatin
-cat klatin/klatin/data/vocab/pl/Makefile.am | sed 's|pl|sk|g' > klatin/klatin/data/vocab/sk/Makefile.am
-
-## install kig examples
-sed -i 's|noinst_DATA|examplesdir = $(kde_datadir)/kig/examples\nexamples_DATA|' kig/examples/Makefile.am
-
-## /usr/bin/ld: cannot find -ltqt-mt/-ltqt - for kstars/indi build
-[[ $TDEVERSION == cgit ]] && \
-sed -i 's|(QT_LDFLAGS|(TQT_LDFLAGS|' kstars/kstars/indi/Makefile.am
-
-ltoolupdate_fn
-
 chown_fn
 
 cd_builddir_fn
 
-CFLAGS="$SLKRCFLAGS" \
-CXXFLAGS="$SLKRCFLAGS" \
-CC=$COMPILER \
-CXX=$COMPILER_CXX \
-../configure \
-   --prefix=$INSTALL_TDE \
-   --disable-rpath \
-   --enable-closure
+# ### Kalzium Chemical Equation Solver - start
+## Needs OCaml and facile
+ocaml_installed_fn () { [[ -s /usr/local/lib$LIBDIRSUFFIX/libnums.a ]] && \
+[[ -s /usr/local/lib$LIBDIRSUFFIX/facile/facile.a ]] ;}
+## If they are already installed, go to OCAML="ON"
+ocaml_installed_fn || {
+## otherwise, if the source archives are in 'src' ..
+[[ -s $BUILD_TDE_ROOT/src/4.05.0.tar.gz ]] && \
+[[ -s $BUILD_TDE_ROOT/src/facile-1.1.3.tar.gz ]] && {
+## .. build, package, and install them
+(
+## ocaml:
+echo -e "\n building ocaml \n"
 
-true # don't go to cmake if ./configure fails
+cd /$TMP_BUILD
+tar xf $BUILD_TDE_ROOT/src/4.05.0.tar.gz
+cd ocaml-4.05.0/
 
-} || {
+./configure -cc $COMPILER -libdir /usr/local/lib$LIBDIRSUFFIX
+## finish build with -j1 if there are race condition errors
+make ${NUMJOBS:-} world.opt || make world.opt
+DESTDIR=$TMP_BUILD/package-ocaml make install
 
-chown_fn
+cd $TMP_BUILD/package-ocaml
+makepkg -l y -c n $OUTPUT/ocaml-4.05.0-x86_64-1.txz
+installpkg $OUTPUT/ocaml-4.05.0-x86_64-1.txz
 
-cd_builddir_fn
+## facile:
+echo -e "\n building facile \n"
 
-## The Kalzium Chemical Equation Solver needs OCaml
-OCAML=OFF
+cd /$TMP_BUILD
+tar xf $BUILD_TDE_ROOT/src/facile-1.1.3.tar.gz
+cd facile-1.1.3/
+
+sed -i 's|mkdir|& -p|' Makefile
+./configure
+make
+make FACILEDIR=$TMP_BUILD/package-facile/usr/local/lib$LIBDIRSUFFIX/facile install
+
+cd $TMP_BUILD/package-facile
+makepkg -l y -c n $OUTPUT/facile-1.1.3-x86_64-1.txz
+installpkg $OUTPUT/facile-1.1.3-x86_64-1.txz
+)
+echo -e "\n returning to building tdeedu \n"
+ocaml_installed_fn || { echo -e " installation of ocaml/facile failed \n" ; exit 1 ; }
+}
+} && \
+OCAML="ON"
+# ### Kalzium Chemical Equation Solver - end
+
+## kig python scripting support
+[[ $(ls -1 /usr/lib$LIBDIRSUFFIX/libboost_python*.so) ]] && KIG_PS="ON"
 
 cmake \
     -DCMAKE_C_FLAGS="$SLKRCFLAGS" \
@@ -113,10 +118,11 @@ cmake \
     -DPLUGIN_INSTALL_DIR=$INSTALL_TDE/lib$LIBDIRSUFFIX/$PLUGIN_INSTALL_DIR \
     -DLIB_SUFFIX=$LIBDIRSUFFIX \
     -DMAN_INSTALL_DIR=$INSTALL_TDE/man \
-    -DWITH_GCC_VISIBILITY="OFF" \
     -DWITH_ARTS="ON" \
-    -DWITH_OCAML_SOLVER=$OCAML \
+    -DWITH_GCC_VISIBILITY="OFF" \
+    -DWITH_KIG_PYTHON_SCRIPTING=${KIG_PS:-"OFF"} \
     -DWITH_LIBUSB="ON" \
+    -DWITH_OCAML_SOLVER=${OCAML:-"OFF"} \
     -DWITH_V4L="ON" \
     -DBUILD_BLINKEN="ON" \
     -DBUILD_KALZIUM="ON" \
@@ -140,8 +146,6 @@ cmake \
     -DBUILD_DOC="ON" \
     -Wno-dev \
     ..
-
-}
 
 ## remove obsolete tags
 doxygen -u doc/kig/scripting-api/Doxyfile.scripting-api
