Patch for inkscape for poppler 21.11 and version update Added verbose [configuration only] and no warning options to tqt3 build

diff --git a/Misc/inkscape/inkscape.SlackBuild b/Misc/inkscape/inkscape.SlackBuild
--- a/Misc/inkscape/inkscape.SlackBuild
+++ b/Misc/inkscape/inkscape.SlackBuild
@@ -24,60 +24,26 @@
 #   SUCH DAMAGE.
 
 PRGNAM=inkscape
-## store version for later use to set $version for package name -
-## too late for log file name, but sort that out when Sl current is released as Sl 15
-## and this script updated for v1.x.x only
-echo 0.92.4 > $TMPVARS/INKSC_VERS && {
-## v 1.1 for Slackware current
-[[ $(ls /var/log/packages/poppler-*) == *-2[1-9].* ]] && echo 1.1 > $TMPVARS/INKSC_VERS ; }
-VERSION=$(cat $TMPVARS/INKSC_VERS)
+VERSION=1.1.1
 BUILD=${BUILD:-1}
 
-ARCHIVE_TYPE="tar.bz2" && [[ $VERSION == 1.1 ]] && ARCHIVE_TYPE="tar.xz"
+ARCHIVE_TYPE="tar.xz"
 SRCURL="https://media.inkscape.org/dl/resources/file/$PRGNAM-$VERSION.$ARCHIVE_TYPE"
 
 source ../../get-source.sh
 ## need this here for CXX_FLAGS for double-conversion
 getsource_fn
 
-## inkscape v1.1 for Slackware current needs gdl and double-conversion
+## inkscape v1.1.1 needs double-conversion
 [[ $(cat $TMPVARS/PRE_DOWNLOAD) != yes ]] && {
-# ### gdl and double-conversion  - start
-[[ $(ls /var/log/packages/poppler-*) == *-2[1-9].* ]] && {
-## If they are already installed, go to end
-[[ -s /usr/local/lib$LIBDIRSUFFIX/libgdl-3.so ]] && \
+# ### double-conversion  - start
+{
+## If it is already installed, go to end
 [[ -s /usr/local/lib$LIBDIRSUFFIX/libdouble-conversion.so ]] || {
-## otherwise, if the source archives are in 'src' ..
-[[ -s $BUILD_TDE_ROOT/src/gdl-3.34.0.tar.xz ]] && \
+## otherwise, if the source archive is in 'src' ..
 [[ -s $BUILD_TDE_ROOT/src/double-conversion-3.1.5.tar.gz ]] && {
-## .. build, package, and install them
+## .. build, package, and install ..
 (
-## gdl:
-echo -e "\n building gdl \n"
-
-cd /$TMP_BUILD
-rm -rf *gdl*
-tar xf $BUILD_TDE_ROOT/src/gdl-3.34.0.tar.xz
-cd gdl-3.34.0
-
-LOCALES=$(cat po/LINGUAS)
-rm po/LINGUAS
-for locale in $I18N
- do
- [[ $LOCALES == *$locale* ]] && echo $locale >> po/LINGUAS
- done
-
-[[ $(cat $TMPVARS/BuildOptions) == *no_warn* ]] && C_Flags='CFLAGS=-w'
-./configure --libdir=/usr/local/lib$LIBDIRSUFFIX ${C_Flags:-}
-
-PKG=$TMP_BUILD/package-gdl
-make_fn
-
-cd $TMP_BUILD/package-gdl
-makepkg -l y -c n $OUTPUT/gdl-3.34.0-$ARCH-$BUILD.txz
-installpkg $OUTPUT/gdl-3.34.0-$ARCH-$BUILD.txz
-
-## double-conversion:
 echo -e "\n building double-conversion \n"
 
 cd /$TMP_BUILD
@@ -86,7 +52,7 @@ tar xf $BUILD_TDE_ROOT/src/double-conversion-3.1.5.tar.gz
 cd double-conversion-3.1.5/
 
 cd cmake/
-# LIBDIRSUFFIX not required - builds to lib$LIBDIRSUFFIX ..
+# LIBDIRSUFFIX not required - builds to lib64 where appropriate ..
 cmake ${G_NINJA:-} ../ -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_FLAGS="$SLKCFLAGS"
 
 PKG=$TMP_BUILD/package-double-conversion
@@ -96,35 +62,39 @@ cd $TMP_BUILD/package-double-conversion
 makepkg -l y -c n $OUTPUT/double-conversion-3.1.5-$ARCH-$BUILD.txz
 installpkg $OUTPUT/double-conversion-3.1.5-$ARCH-$BUILD.txz
 )
-echo -e "\n returning to building inkscape \n"
-} || { ## .. but if the source archives aren't in 'src', display message ..
-echo -e "\n ############ \n\n\033[39;1m gdl and/or double-conversion are not installed and are required for this build \n \033[34;1m
+echo -e "\n now building inkscape \n"
+} || { ## .. but if the source archive isn't in 'src', display download URL ..
+echo -e "\n ############ \n\n\033[39;1m double-conversion is not installed and is required for this build \n \033[34;1m
  Download:
-\n wget -O $BUILD_TDE_ROOT/src/gdl-3.34.0.tar.xz https://download.gnome.org/sources/gdl/3.34/gdl-3.34.0.tar.xz
 \n wget -O $BUILD_TDE_ROOT/src/double-conversion-3.1.5.tar.gz https://github.com/google/double-conversion/archive/v3.1.5.tar.gz
 \n and re-run this script .. \n\n \033[0m ############ \n" ; exit 1 ; }
 }
 }
-# ### gdl and double-conversion - end
+# ### double-conversion - end
 }
 
 untar_fn
 
-## install to .../lib64 on 64-bit system
-## add -DLIB_SUFFIX=$LIBDIRSUFFIX to cmake
-[[ -d /lib64 ]] && {
-## set RPATH
-sed -i 's|ORIGIN/../lib/inkscape|ORIGIN/../lib${LIB_SUFFIX}/inkscape|' CMakeLists.txt
-## set output directory
-sed -i 's|/lib |/lib${LIB_SUFFIX} |' CMakeLists.txt
-## for dynamic lib
-sed -i 's|lib/inkscape|lib${LIB_SUFFIX}/inkscape|' src/CMakeLists.txt
-## for static libs
-sed -i 's|lib/inkscape|lib${LIB_SUFFIX}/inkscape|' CMakeScripts/HelperMacros.cmake
-}
+## patch for poppler 21.11
+## https://gitlab.com/inkscape/inkscape/-/commit/5724c21b9cb7b6176a7b36ca24068b148c817e82.diff
+echo $'--- src/extension/internal/pdfinput/pdf-parser.cpp
++++ src/extension/internal/pdfinput/pdf-parser.cpp
+@@ -2171,3 +2171,7 @@
+     printf("  font: tag=%s name='\''%s'\'' %g\n",
++#if POPPLER_CHECK_VERSION(21,11,0)
++	   font->getTag().c_str(),
++#else
+ 	   font->getTag()->getCString(),
++#endif
+ 	   font->getName() ? font->getName()->getCString() : "???",
+' | patch -p0
+
+## set internal 2geom lib paths to lib$LIBDIRSUFFIX
+sed -i "s|CMAKE_INSTALL_PREFIX}/lib|&$LIBDIRSUFFIX|" src/3rdparty/2geom/CMakeLists.txt
+sed -i "s|DESTINATION lib|&$LIBDIRSUFFIX|" src/3rdparty/2geom/CMakeLists.txt
+sed -i "s|libdir=.*$|&$LIBDIRSUFFIX|" src/3rdparty/2geom/2geom.pc.in
 
 ## only build for required locales
-# ### TODO tidy up when Sl 15 released and v0.92.4 no longer built
 {
 ## set up a directory to store the required locale files temporarily
 TEMP_DIR=$TMP_BUILD/tmp-$PRGNAM/loc_tmp
@@ -147,24 +117,6 @@ for locale in $I18N
 rm -rf po/*.po
 mv $TEMP_DIR/* po/
 
-## .. for READMEs
-for locale in $I18N
- do
- mv README.$locale.txt $TEMP_DIR
- done
-rm README.*.txt
-mv $TEMP_DIR/* .
-RM_LIST=$(ls -1 README*)
-
-## .. for keys.*.html
-for locale in $I18N
- do
- mv doc/keys.$locale.html $TEMP_DIR
- done
-rm doc/keys.*.html
-mv $TEMP_DIR/* doc/
-KEYS_LIST=$(ls -1 doc/keys.*)
-
 ## .. for tutorials
 for locale in $I18N
  do
@@ -172,17 +124,8 @@ for locale in $I18N
  done
 rm share/tutorials/*.*.*
 mv $TEMP_DIR/* share/tutorials/
+} || true # because the existence of the files hasn't been tested
 
-## .. for templates
-for locale in $I18N
- do
- mv share/templates/*.$locale.* $TEMP_DIR
- done
-rm share/templates/*.*.*
-mv $TEMP_DIR/* share/templates/
-} || true
-
-[[ $VERSION == 1.1 ]] && {
 ## only package man pages for required locales
 for file in man/ink*.*.pod.in
 do
@@ -190,7 +133,18 @@ do
 done
 ## and install them to $prefix, as per most other Slackware packages
 sed -i 's|MANFILE_DEST "${SHARE_INSTALL}|MANFILE_DEST "${CMAKE_INSTALL_PREFIX}|' CMakeScripts/Pod2man.cmake
-}
+
+## only package welcome screen text for required locales
+I18N_SVG="about.svg start-welcome-text.svg"
+#
+for Loc in $I18N
+do
+ [[ -s share/screens/start-welcome-text.$Loc.svg ]] && I18N_SVG="$I18N_SVG start-welcome-text.$Loc.svg" && COUNT_TEXT=$[${COUNT_TEXT:-}+1]
+COUNT_I18N=$[${COUNT_I18N:-}+1]
+done
+## Add the TRANSLATING file if any of the locales has no start-welcome-text.$I18N.svg
+[[ ${COUNT_I18N:-} != ${COUNT_TEXT:-} ]] && I18N_SVG="TRANSLATING $I18N_SVG"
+sed -i "s|\"\*.svg\"|$I18N_SVG|" share/screens/CMakeLists.txt
 
 listdocs_fn
 
@@ -198,11 +152,7 @@ chown_fn
 
 cd_builddir_fn
 
-## default options have been pulled from CMakeLists.txt
-## These next two determine the RPATH for the inkscape library relative to the binary:
-## INKSCAPE_INSTALL_LIBDIR is an addition for v1.1 and is relative to CMAKE_INSTALL_PREFIX/
-## LIB_SUFFIX is used for v0.92.4
-#
+## options have been pulled from CMakeLists.txt
 cmake ${G_NINJA:-} \
     -DCMAKE_C_FLAGS="$SLKCFLAGS" \
     -DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
@@ -210,9 +160,8 @@ cmake ${G_NINJA:-} \
     -DCMAKE_CXX_COMPILER=$COMPILER_CXX \
     -DCMAKE_BUILD_TYPE=Release \
     -DCMAKE_INSTALL_PREFIX=/usr/local \
-    -DINKSCAPE_INSTALL_LIBDIR=lib$LIBDIRSUFFIX/inkscape \
-    -DLIB_SUFFIX=$LIBDIRSUFFIX \
     -DBUILD_SHARED_LIBS="ON" \
+    -DBUILD_TESTING="OFF" \
     -DENABLE_BINRELOC="OFF" \
     -DENABLE_LCMS="ON" \
     -DENABLE_POPPLER="ON" \
@@ -220,16 +169,15 @@ cmake ${G_NINJA:-} \
     -DWITH_ASAN="OFF" \
     -DWITH_DBUS="OFF" \
     -DWITH_FUZZ="OFF" \
-    -DWITH_GNOME_VFS="ON" \
+    -DWITH_GNU_READLINE="ON" \
     -DWITH_GRAPHICS_MAGICK="ON" \
-    -DWITH_GTK3_EXPERIMENTAL="OFF" \
-    -DWITH_GTKSPELL="OFF" \
+    -DWITH_GSPELL="OFF" \
     -DWITH_IMAGE_MAGICK="ON" \
-    -DWITH_INKJAR="ON" \
+    -DWITH_INTERNAL_2GEOM="ON" \
     -DWITH_JEMALLOC="OFF" \
     -DWITH_LIBCDR="ON" \
-    -DWITH_LIBVISIO="ON" \
-    -DWITH_LIBWPG="ON" \
+    -DWITH_LIBVISIO="OFF" \
+    -DWITH_LIBWPG="OFF" \
     -DWITH_LPETOOL="OFF" \
     -DLPE_ENABLE_TEST_EFFECTS="OFF" \
     -DWITH_MANPAGE_COMPRESSION="ON" \
@@ -244,25 +192,6 @@ make_fn
 
 INSTALL_TDE="/usr/local"
 installdocs_fn
-
-[[ $VERSION == 0.92.4 ]] && {
-## only package man pages for required locales
-mkdir -p $PKG/usr/man/man1/
-mv $PKG/usr/local/share/man/man1/* $PKG/usr/man/man1/
-rm -rf $PKG/usr/local/share/man
-{ for locale in $I18N
- do
- [[ -s $PKG/usr/man/man1/inkscape.$locale.1 ]] && mv $PKG/usr/man/man1/inkscape.$locale.1 $TEMP_DIR
- done
-rm $PKG/usr/man/man1/inkscape.*.1
-mv $TEMP_DIR/* $PKG/usr/man/man1/
-rm -rf $TEMP_DIR
-} || true
-
-## man pages are gzipped by WITH_MANPAGE_COMPRESSION="ON" for 1.1
-INSTALL_TDE=/usr
-mangzip_fn
-}
 
 strip_fn
 
